# Generated by Django 4.1.4 on 2023-04-17 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webpage',
            old_name='email',
            new_name='mail',
        ),
    ]
